CREATE TABLE IF NOT EXISTS todo (
    id SERIAL PRIMARY KEY,
    content TEXT NOT NULL,
    done BOOLEAN,
    done_datetime TIMESTAMP WITH TIME ZONE,
    regist_datetime TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_datetime TIMESTAMP WITH TIME ZONE
)
;
