version: '3'

services:
  db:
    container_name: local_db_container_pg15
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
    - postgresql-volume-pg15:/var/lib/postgresql/data
    ports:
    - 5434:5432

volumes:
  postgresql-volume-pg15:
    name: postgresql-volume-pg15
    driver: local

